Use as default date today and as default city NY
merapar/gracenote-react-demo pull request #4
Opened 2023-04-01 01:47 UTC by JaapHaitsma

My first PR ever for a React project. Not sure it is useful as with material UI you probably have many changes. Just wanted to get some practice for React.

If useful commit if not you can just delete. I'm just happy that I made something work in React

2023-04-03 11:53 UTC, mzielonkowski-merapar requested changes
please change code with my comments

2023-04-03 11:53 UTC, mzielonkowski-merapar commented on src/pages/LandingPage.tsx
> +const getDateString = () => {
we have ./src/utils/getTodayDateISO.ts , please use that function getTodayDateISO() to get ISO date

2023-04-03 11:53 UTC, mzielonkowski-merapar commented on src/pages/LandingPage.tsx
> +  const [zipcode, setZipcode] = useState(11554);
this 11554 is so called magic number, please use const for it to keep it with nice name (as seen in the PR's name it is NYC one of zipcodes)

2023-04-10 18:55 UTC, JaapHaitsma commented
Sorry @mzielonkowski-merapar I missed your comments. Agree with them but as you guys will move the code to material UI datepicker it does not make that much sense to still merge this

2023-04-10 18:55 UTC, closed without merging